version: '3'

services:

  backend:
    container_name: app_backend
    build: ./backend
    ports: 
      - 8080:8080
    networks:
      - mynetwork
  
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports: 
      - 8501:8501
    depends_on:
      - backend
    networks:
      - mynetwork
    
networks:
  mynetwork: